force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Classs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Class</relationshipLabel>
    <relationshipName>Class</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FirstVFPageController.cls
public class FirstVFPageController {
    public Class__c clas {get;set;}
    public Boolean showDetails {get;set;}
    public String accountId {get;set;}
    
    public FirstVFPageController(ApexPages.StandardController stdController) {
        clas = [SELECT Name From Class__c WHERE Account__c = :stdController.getId()];
        showDetails = true;
    }
    
    public void toggleDetails() {
    	showDetails = !showDetails;
    }
}