force-app/main/default/objects/Account/fields/Contact_Types__c.field-meta.xml
<CustomField>
    <fullName>Contact_Types__c</fullName>
    <label>Contact Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RollUpTriggerManager.cls
public class RollUpTriggerManager {
    public static void rollUpValues(Set<Id> accIdSet) {
    	Set<String> fieldValueSet = new Set<String>();
        List<Account> parentsToUpdate = [SELECT Id, Name, (SELECT Id, Name, Type__c 
                                                           FROM Contacts) 
                                         FROM Account
                                         WHERE Id = :accIdSet];
        for (Account acc : parentsToUpdate) {
            fieldValueSet = new Set<String>();
            for (Contact con : acc.Contacts) {
                fieldValueSet.add(con.Type__c);
            }
            List<String> concatenateList = new List<String>(fieldValueSet);
            acc.Contact_Types__c = String.join(concatenateList, ',');
        }
        update parentsToUpdate;
    }
}