force-app/main/default/objects/Account/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountNotes__c/AccountNotes__c.object-meta.xml
<CustomObject>
    <label>AccountNotes</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>AccountNotes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountNotes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountNotes</relationshipLabel>
    <relationshipName>AccountNotes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountNotes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <referenceTo>Notes__c</referenceTo>
    <relationshipLabel>AccountNotes</relationshipLabel>
    <relationshipName>AccountNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UserNoteController.cls
public class UserNoteController {
	public User usr {get;set;}
	public Notes__c note {get;set;}
	public String userId {get;set;}
	public String accId {get;set;}
	public String noteId {get;set;}
	public List<SelectOption> accountList{get;set;}
	public List<SelectOption> noteList{get;set;}
	public boolean showDetails{get;set;}
	public UserNoteController(){
		showDetails = true;
		accountList = new List<SelectOption>();
		accountList.add(new SelectOption('','None'));
        String userId=ApexPages.currentPage().getParameters().get('aId');
        if(userId != null){
	        List<User> usrList= [SELECT Name, Id FROM User WHERE Id = :userId];
	        if(usrList.size() > 0) {
	            usr = usrList[0];
	        }
        }
        else{
        	userId = UserInfo.getUserId();
            List<User> usrList= [SELECT Name, Id FROM User WHERE Id = :userId];
        	if(usrList.size() > 0) {
            	usr = usrList[0];
       		}
        }
        for(Account acc : [Select Id, Name, AccountNumber from Account WHERE User__c = :userId]){
			accountList.add(new SelectOption(acc.Id,acc.Name));
		}
    }
    
    public void selected(){
		showDetails = true;
		noteList = new List<SelectOption>();
		noteList.add(new SelectOption('','None'));
		for(AccountNotes__c accnote : [SELECT Name, Id, Notes__r.Id, Notes__r.Title__c
                           				 FROM AccountNotes__c WHERE Account__c = :accId]){
				noteList.add(new SelectOption(accnote.Notes__r.Id, accnote.Notes__r.Title__c));
		}
		
    }
    
	public void selected2(){
		showDetails = true;
		List<Notes__c> noteList = [SELECT Name, Id, Title__c, Description__c, Private__c FROM Notes__c WHERE Id = :noteId];
	    if(noteList.size() > 0) {
	    	note = noteList[0];
	    }
	    showDetails = !note.Private__c;
	}
	
	public void edit() {
            if (note.Private__c) {                     
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Note is Private');
            ApexPages.addMessage(errMsg);
            }
            else {
            update note;
            ApexPages.Message okMsg = new ApexPages.Message(ApexPages.Severity.INFO,'INFO: Save Success');
            ApexPages.addMessage(okMsg);
            }
    }
}