force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one
or more positions</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <externalId>true</externalId>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <externalId>true</externalId>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/classes/UtilityTest.cls
public class UtilityTest {

    public Candidate__c createCandidate(Integer i, Boolean isInsert) {
        Candidate__c can = new Candidate__c();
        can.First_Name__c = 'Test' + i;
        can.Last_Name__c = 'Test' + i;
        can.Email__c = 'Test' + i + '@test.com';
        can.Date_Of_Birth__c = System.today().addDays(-7000);
        if(isInsert) {
            insert can;
        }
        return can;        
    }

    public Contact createContact(Integer i) {
        Contact con = new Contact();
        con.FirstName = 'Test' + i;
        con.LastName = 'Test' + i;
        con.Email = 'Test' + i + '@test.com';
        return con;        
    }
}