force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one
or more positions</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Represents a candidate&apos;s application to a position</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateController.cls
public class CandidateController {
    
    public class CandidateWrapper {
        string candidateName = '';
        string jobAppName = '';
        string hiringManagerName = '';
    }
    public void fetchData() {
        CandidateWrapper canObj;
        List<CandidateWrapper> wrapObj = new List<CandidateWrapper>();
        Map<String, List<CandidateWrapper>> mapCanWrap = new Map<String, List<CandidateWrapper>>();
     	List<SelectOption> listCity = new List<SelectOption>();
        
    	for(Candidate__c can : [SELECT Name, City__c,
                               		(SELECT Name, Position__r.Hiring_Manager__r.FirstName
                                 	 FROM Job_Applications__r)
                                FROM Candidate__c]) 
        {                        
        	for(Job_Application__c ja : can.Job_Applications__r) {
            	canObj = new CandidateWrapper();
                canObj.candidateName = can.Name;
                canObj.jobAppName = ja.Name;
        		canObj.hiringManagerName = ja.Position__r.Hiring_Manager__r.FirstName;
                wrapObj.add(canObj);
        	}
            
            if(!mapCanWrap.containsKey(can.City__C)) {
            	mapCanWrap.put(can.City__c, new List<CandidateWrapper>());
                listCity.add(new SelectOption(can.City__c, can.City__c));
            }
            mapCanWrap.get(can.City__c).addAll(wrapObj);  
    	}
    }
}